<!-- TODO:PHP For File Scan Upload -->

<!-- HTML -->
<!DOCTYPE html>
<html lang="en" dir="ltr">

  <head>
    <meta charset="utf-8">
    <title>Fatoora</title>
    <!-- StyleSheet -->
    <link rel="stylesheet" href="CSS/scan_styles.css">

    <!-- Font Awsome Kit  -->
    <script src="https://kit.fontawesome.com/4a82e10df4.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <!-- Navigation Bar From Template -->
    <?php include 'Templates/navbar.php' ?>

    <!-- Main Division -->
    <div class="container">

      <!--Scan Form  -->
        <form id="scan-form" class="scan-form" action="Scan.php" method="post">
          <span class="form-title">Upload Receipt</span>

          <!-- File Upload Input -->
            <input type="file" name="receipt-scan" class="receipt-scan-input" id="receipt-scan-input"/>

          <!-- People list Div -->
            <div class="people-list-div" id="people-list-div">
              <!-- Div Title -->
              <span class="people-list-title">People:</span>
              <!-- Person Name Input Fields Generated by JS-->

              <!-- Add Person Button -->

                <svg class="add-person-in-list-btn" id="add-person-in-list-btn" viewBox="0 0 100 100">
                  <circle cx="50" cy="50" r="45" fill="none" stroke-width="7.5"></circle>
                  <line x1="32.5" y1="50" x2="67.5" y2="50" stroke-width="5"></line>
                  <line x1="50" y1="32.5" x2="50" y2="67.5" stroke-width="5"></line>
                </svg>

            </div>

            <!-- Hidden Attribute to Store a list of all members generated by the JS file Scan.js in Section 2 -->
            <input type="hidden" name="Members" value="" id="all-members-list">

            <!-- TODO: Change Type to Submit -->
            <input type="button" name="new-scan" value="Go Fatoora" class="submit-fatoora-scan-btn" id="submit-fatoora-scan-btn">

        </form>
    </div>

    <?php include 'Templates/footer.php' ?>
    <!-- Script Refrences -->
      <script src="Scripts/Scan.js"></script>
  </body>
</html>


<!--
Class List:
  container
  scan-form
  receipt-scan-input

  people-list-div
  people-list-title
  person-in-list-input
  add-person-in-list-btn
  submit-fatoora-scan-btn
 -->
