<!-- TODO:PHP For File Scan Upload -->

<!-- HTML -->
<!DOCTYPE html>
<html lang="en" dir="ltr">

  <head>
    <meta charset="utf-8">
    <title>Fatoora</title>
    <!-- Font Awsome Kit  -->
    <script src="https://kit.fontawesome.com/4a82e10df4.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <!-- Navigation Bar From Template -->
    <?php include 'Templates/navbar.php' ?>

    <!-- Main Division -->
    <div class="container">

      <!--Scan Form  -->
        <form id="scan-form" class="scan-form" action="Scan.php" method="post">

          <!-- File Upload Input -->
            <input type="file" name="receipt-scan" class="receipt-scan-input" id="receipt-scan-input"/>

          <!-- People list Div -->
            <div class="people-list-div" id="people-list-div">
              <!-- Div Title -->
              <span class="people-list-title">People:</span>
              <!-- Person Name Input Fields -->
              <input type="text" name="person-in-list-input" placeholder="Member X" class="person-in-list-input" id="person-in-list-input"/>
              <!-- Add Person Button -->
              <input type="button" name="add-person" value="+" class="add-person-in-list-btn" id="add-person-in-list-btn"></input>
            </div>

            <!-- Hidden Attribute to Store a list of all members generated by the JS file Scan.js in Section 2 -->
            <input type="hidden" name="Members" value="" id="all-members-list">

            <!-- TODO: Change Type to Submit -->
            <input type="button" name="new-scan" value="Submit Fatoora" class="submit-fatoora-scan-btn" id="submit-fatoora-scan-btn">
        </form>
    </div>

    <!-- Script Refrences -->
      <script src="Scripts/Scan.js"></script>
  </body>
</html>


<!--
Class List:
  container
  scan-form
  receipt-scan-input

  people-list-div
  people-list-title
  person-in-list-input
  add-person-in-list-btn
  submit-fatoora-scan-btn
 -->
